main: net.novauniverse.novashop.NovaShop
name: NovaShop
description: A shop plugin
version: 1.0

depend: [NovaCore, Vault]

permissions:
   novapixelmon.joinfullserver:
       description: Allow players to join even if the server is full
       default: op